### ISSUE TITLE
Question: fix:ios ?

### ISSUE THREAD

**Issue by rborn** [pavjacko/react-native-vanilla#3]
Hi, 
This looks like an amazing helper to kickstart a multi platform project 🎉

Could explain why is needed the [`fix:ios`](https://github.com/pavjacko/react-native-vanilla/blob/master/package.json#L35) step in setup ?

Thank you 🤗

**Comment by pavjacko** [comment]
@rborn Thanks!
it is because latest version of react-native doesn't play nicely with cocoapods and objc imports.
This issue been around for a while unfortunately,  so until it will been fixed by RN I use this "hack" to get around this problem.

More info on issue here:
https://github.com/facebook/react-native/issues/13198

**Comment by rborn** [comment]
great, thank you ❤️
